### ISSUE TITLE
Bookmarked PR title does not sync after editing PR title in GH

### ISSUE THREAD

**Issue by vlvagerviwager** [tborychowski/github-browser#18]
How to reproduce this issue:

1. Bookmark a PR
2. Edit the title of the PR
3. The bookmark title is still the old PR title, even after hitting Cmd + R or the refresh icon

**Comment by tborychowski** [comment]
This is a bit of a problem.
The way it works currently:
- bookmark event occurs
- issue details are stored to the DB
- only thing that updates is the `lastVisitedDate` when you visit the page

The reason for the title to not update is that the required solution would have to make a lot of additional requests to the GH server at some point, e.g.
- there is no way to detect the title change (without a hacky way to attach onSubmit events directly on the page)
- all bookmarked issues would have to be checked periodically to make sure that the metadata is in sync

I will think about that :-)
