### ISSUE TITLE
Github Browser Helper processes

### ISSUE THREAD

**Issue by vlvagerviwager** [tborychowski/github-browser#19]
<img width="371" alt="screen shot 2017-04-26 at 09 14 18" src="https://cloud.githubusercontent.com/assets/5951798/25425836/245354fc-2a65-11e7-886b-e287d29d21eb.png">

Related to the Google Chrome Helper on macOS, I suppose. Would be good to look into this and see if anything can be done.

**Comment by tborychowski** [comment]
wow! I haven't seen that before!
Will investigate, thanks!

**Comment by tborychowski** [comment]
and it seems that this happens because of the skeleton-loading animation (even if it is not visible all the time).
crazy!

anyways, [fix committed](https://github.com/tborychowski/github-browser/commit/7740a490640439c386531e380b6ae1bcbd8c285b) and will be available in the next release.
Thanks!
