### ISSUE TITLE
Change request: give indication that link has been copied

### ISSUE THREAD

**Issue by vlvagerviwager** [tborychowski/github-browser#22]
![screen shot 2017-04-27 at 16 14 58](https://cloud.githubusercontent.com/assets/5951798/25490436/bfa5faf4-2b64-11e7-8ea2-254292667e0d.png)

It would be nice to give an indication to the user after clicking on the button, to let them know that the link has been copied. Currently after it's clicked, it's not clear what happened, or if anything happened.

**Comment by tborychowski** [comment]
is this button even useful? what if I removed if?
you can copy the URL by clicking on the address-bar and hitting cmd+c...

**Comment by vlvagerviwager** [comment]
@tborychowski: Buuuuuut Cmd + C in GHB doesn't always work :)

Aside from that, I think it has (some) value - 1 click vs. 2 keys. It also assists people who aren't computer literate, and some people like to use visual cues to do stuff.
