### ISSUE TITLE
Impossible to install on Ubuntu 

### ISSUE THREAD

**Issue by asitemade4u** [tborychowski/github-browser#46]
Hi Tom,
I attach the installation log with several errors.

[2017-08-18T20_24_59_764Z-debug.log.zip](https://github.com/tborychowski/tim/files/1235593/2017-08-18T20_24_59_764Z-debug.log.zip)

**Comment by tborychowski** [comment]
Hello,

It seems that there's an error with one of the 3rd parties:
```sh
1172 verbose stack Error: keyboard-layout@2.0.13 install: `node-gyp rebuild`
```

This (`node-gyp rebuild` error) happens every once in a while with some modules.
I've seen it in many other projects and it varies from machine to machine (sometimes it happens on windows but not on mac, other times on mac but not on linux).
It's a weird one and difficult to fix.

could you try to install this dependency manually, and see if you get this error too?
```sh
npm i keyboard-layout@2.0.13
```

If you don't, please install `node-gyp` globally:
```sh
npm i -g node-gyp
```

and try again by running (in `TIM` folder):
```sh
npm i --no-optional
```

**Comment by asitemade4u** [comment]
Hi Tom,

I tried by:

 1. installing node-gyp globally
 2. then installing the keyboard-layout locally in the folder

Both failed -- log attached.

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by tborychowski** [comment]
I'm sorry, but at that point I don't how to help you...
It seems that you're missing some dev libs required to rebuild other libs or something like that.

Can I suggest to go through the threads like these:
- https://github.com/nodejs/node-gyp/issues/1032
- https://github.com/nodejs/node-gyp/issues/809

**Comment by asitemade4u** [comment]
Another solution would be to be able to download a pre-built version, as most Electron app developers allow.


Stephen Sinclair ASiteMade4U On Sat, Aug 19, 2017 at 3:17am, Tomasz Borychowski < notifications@github.com [notifications@github.com] > wrote:
I'm sorry, but at that point I don't how to help you...
It seems that you're missing some dev libs required to rebuild other libs or something like that.

Can I suggest to go through the threads like these:

 * nodejs/node-gyp#1032 [https://github.com/nodejs/node-gyp/issues/1032]
 * nodejs/node-gyp#809 [https://github.com/nodejs/node-gyp/issues/809]

**Comment by tborychowski** [comment]
I don't  have a linux machine to actually test that the app works. Sorry.
As this problem is unrelated to and unfixable in the source code of my app, I'm closing this.

**Comment by vokiel** [comment]
I solved the issue with dependencies by installing those packages:
```
$ sudo apt install libxext-dev libxtst-dev libxkbfile-dev
```

Then regular
```
$ npm i
# missing dependency
$ npm i ajv@5.2.2
```

But still, app didn't run:
```
$ npm start

> tim@3.1.0 start /home/vokiel/bin/tim
> electron index.js

App threw an error during load
Error: Cannot find module './app/services/events'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/vokiel/bin/tim/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vokiel/bin/tim/index.js:3:15)
    at Object.<anonymous> (/home/vokiel/bin/tim/index.js:59:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
Env:
```
$ node -v
v6.11.1
$ npm -v
3.10.10
```

**Comment by tborychowski** [comment]
Thanks @vokiel!
Yes, you're right, I missed 1 step in my [dev-install](https://github.com/tborychowski/tim/blob/master/README.md#dev-install) instructions.

You need to run `gulp` before starting the app.

**Comment by vokiel** [comment]
It works!

Well done :1st_place_medal:

**Comment by asitemade4u** [comment]
Yes it does, thank you guys!
