### ISSUE TITLE
Two-factor authentication is not working

### ISSUE THREAD

**Issue by vokiel** [tborychowski/github-browser#49]
GitHub redirects to another page, where one can put auth code (sent in SMS), but Tim redirects again to `/login` address.

![2FA dialog](https://help.github.com/assets/images/help/2fa/2fa-dialog.png)

**Comment by tborychowski** [comment]
Thanks. I will have a look when I get the chance.

**Comment by tborychowski** [comment]
The fix is now in master.
Release will follow.
Thanks for reporting the bug!
