### ISSUE TITLE
Feature Request : Integration to work with Gitlab

### ISSUE THREAD

**Issue by MohammadWaleed** [tborychowski/github-browser#54]
i really liked the app, and i would love to see it work with gitlab 
what is the possibility of that happening ?

**Comment by tborychowski** [comment]
Thanks :-)

As for GitLab - unfortunately, this is not on my todo list :-)
It should not be too difficult to adopt, as the abstraction of the backend layer should be sufficient.
But I don't have enough free time to make it happen.
But you're welcome to fork it or make a PR :-)
