### ISSUE TITLE
Login not working when 2-factor-auth enabled on github

### ISSUE THREAD

**Issue by cadorn** [tborychowski/github-browser#57]
After login it flashes to the 2-factor-auth page and then back to the login page.

**Comment by tborychowski** [comment]
hi.
I didn't realised that anyone's actually using this ;-)

As for the issue, I know about this. 
Unfortunately, I don't have enough time recently to work on this project anymore.
(I will try to make time, but can't promise anything).

I'd welcome a PR though :-)

**Comment by cadorn** [comment]
I was looking at electron apps and came across yours. Trying to evaluate it to see if it could be useful.

No sweat if you cannot get to fixing it.

I am just casually looking around. I do not have time to get involved either or I would build something myself ;)
